INSERT INTO TuThien.CITY (id, name, region_id) VALUES (1, 'Thành phố Hà Nội', 1);
INSERT INTO TuThien.CITY (id, name, region_id) VALUES (2, 'Tỉnh Hà Giang', 1);
INSERT INTO TuThien.CITY (id, name, region_id) VALUES (3, 'Tỉnh Cao Bằng', 1);
INSERT INTO TuThien.CITY (id, name, region_id) VALUES (4, 'Tỉnh Bắc Kạn', 1);
INSERT INTO TuThien.CITY (id, name, region_id) VALUES (5, 'Tỉnh Tuyên Quang', 1);
INSERT INTO TuThien.CITY (id, name, region_id) VALUES (6, 'Tỉnh Lào Cai', 1);
INSERT INTO TuThien.CITY (id, name, region_id) VALUES (7, 'Tỉnh Điện Biên', 1);
INSERT INTO TuThien.CITY (id, name, region_id) VALUES (8, 'Tỉnh Lai Châu', 1);
INSERT INTO TuThien.CITY (id, name, region_id) VALUES (9, 'Tỉnh Sơn La', 1);
INSERT INTO TuThien.CITY (id, name, region_id) VALUES (10, 'Tỉnh Yên Bái', 1);
INSERT INTO TuThien.CITY (id, name, region_id) VALUES (11, 'Tỉnh Hoà Bình', 1);
INSERT INTO TuThien.CITY (id, name, region_id) VALUES (12, 'Tỉnh Thái Nguyên', 1);
INSERT INTO TuThien.CITY (id, name, region_id) VALUES (13, 'Tỉnh Lạng Sơn', 1);
INSERT INTO TuThien.CITY (id, name, region_id) VALUES (14, 'Tỉnh Quảng Ninh', 1);
INSERT INTO TuThien.CITY (id, name, region_id) VALUES (15, 'Tỉnh Bắc Giang', 1);
INSERT INTO TuThien.CITY (id, name, region_id) VALUES (16, 'Tỉnh Phú Thọ', 1);
INSERT INTO TuThien.CITY (id, name, region_id) VALUES (17, 'Tỉnh Vĩnh Phúc', 1);
INSERT INTO TuThien.CITY (id, name, region_id) VALUES (18, 'Tỉnh Bắc Ninh', 1);
INSERT INTO TuThien.CITY (id, name, region_id) VALUES (19, 'Tỉnh Hải Dương', 1);
INSERT INTO TuThien.CITY (id, name, region_id) VALUES (20, 'Thành phố Hải Phòng', 1);
INSERT INTO TuThien.CITY (id, name, region_id) VALUES (21, 'Tỉnh Hưng Yên', 1);
INSERT INTO TuThien.CITY (id, name, region_id) VALUES (22, 'Tỉnh Thái Bình', 1);
INSERT INTO TuThien.CITY (id, name, region_id) VALUES (23, 'Tỉnh Hà Nam', 1);
INSERT INTO TuThien.CITY (id, name, region_id) VALUES (24, 'Tỉnh Nam Định', 1);
INSERT INTO TuThien.CITY (id, name, region_id) VALUES (25, 'Tỉnh Ninh Bình', 1);
INSERT INTO TuThien.CITY (id, name, region_id) VALUES (26, 'Tỉnh Thanh Hóa', 2);
INSERT INTO TuThien.CITY (id, name, region_id) VALUES (27, 'Tỉnh Nghệ An', 2);
INSERT INTO TuThien.CITY (id, name, region_id) VALUES (28, 'Tỉnh Hà Tĩnh', 2);
INSERT INTO TuThien.CITY (id, name, region_id) VALUES (29, 'Tỉnh Quảng Bình', 2);
INSERT INTO TuThien.CITY (id, name, region_id) VALUES (30, 'Tỉnh Quảng Trị', 2);
INSERT INTO TuThien.CITY (id, name, region_id) VALUES (31, 'Tỉnh Thừa Thiên Huế', 2);
INSERT INTO TuThien.CITY (id, name, region_id) VALUES (32, 'Thành phố Đà Nẵng', 2);
INSERT INTO TuThien.CITY (id, name, region_id) VALUES (33, 'Tỉnh Quảng Nam', 2);
INSERT INTO TuThien.CITY (id, name, region_id) VALUES (34, 'Tỉnh Quảng Ngãi', 2);
INSERT INTO TuThien.CITY (id, name, region_id) VALUES (35, 'Tỉnh Bình Định', 2);
INSERT INTO TuThien.CITY (id, name, region_id) VALUES (36, 'Tỉnh Phú Yên', 2);
INSERT INTO TuThien.CITY (id, name, region_id) VALUES (37, 'Tỉnh Khánh Hòa', 2);
INSERT INTO TuThien.CITY (id, name, region_id) VALUES (38, 'Tỉnh Ninh Thuận', 2);
INSERT INTO TuThien.CITY (id, name, region_id) VALUES (39, 'Tỉnh Bình Thuận', 2);
INSERT INTO TuThien.CITY (id, name, region_id) VALUES (40, 'Tỉnh Kon Tum', 2);
INSERT INTO TuThien.CITY (id, name, region_id) VALUES (41, 'Tỉnh Gia Lai', 2);
INSERT INTO TuThien.CITY (id, name, region_id) VALUES (42, 'Tỉnh Đắk Lắk', 2);
INSERT INTO TuThien.CITY (id, name, region_id) VALUES (43, 'Tỉnh Đắk Nông', 2);
INSERT INTO TuThien.CITY (id, name, region_id) VALUES (44, 'Tỉnh Lâm Đồng', 2);
INSERT INTO TuThien.CITY (id, name, region_id) VALUES (45, 'Tỉnh Bình Phước', 3);
INSERT INTO TuThien.CITY (id, name, region_id) VALUES (46, 'Tỉnh Tây Ninh', 3);
INSERT INTO TuThien.CITY (id, name, region_id) VALUES (47, 'Tỉnh Bình Dương', 3);
INSERT INTO TuThien.CITY (id, name, region_id) VALUES (48, 'Tỉnh Đồng Nai', 3);
INSERT INTO TuThien.CITY (id, name, region_id) VALUES (49, 'Tỉnh Bà Rịa - Vũng Tàu', null);
INSERT INTO TuThien.CITY (id, name, region_id) VALUES (50, 'Thành phố Hồ Chí Minh', 3);
INSERT INTO TuThien.CITY (id, name, region_id) VALUES (51, 'Tỉnh Long An', 3);
INSERT INTO TuThien.CITY (id, name, region_id) VALUES (52, 'Tỉnh Tiền Giang', 3);
INSERT INTO TuThien.CITY (id, name, region_id) VALUES (53, 'Tỉnh Bến Tre', 3);
INSERT INTO TuThien.CITY (id, name, region_id) VALUES (54, 'Tỉnh Trà Vinh', 3);
INSERT INTO TuThien.CITY (id, name, region_id) VALUES (55, 'Tỉnh Vĩnh Long', 3);
INSERT INTO TuThien.CITY (id, name, region_id) VALUES (56, 'Tỉnh Đồng Tháp', 3);
INSERT INTO TuThien.CITY (id, name, region_id) VALUES (57, 'Tỉnh An Giang', 3);
INSERT INTO TuThien.CITY (id, name, region_id) VALUES (58, 'Tỉnh Kiên Giang', 3);
INSERT INTO TuThien.CITY (id, name, region_id) VALUES (59, 'Thành phố Cần Thơ', 3);
INSERT INTO TuThien.CITY (id, name, region_id) VALUES (60, 'Tỉnh Hậu Giang', 3);
INSERT INTO TuThien.CITY (id, name, region_id) VALUES (61, 'Tỉnh Sóc Trăng', 3);
INSERT INTO TuThien.CITY (id, name, region_id) VALUES (62, 'Tỉnh Bạc Liêu', 3);
INSERT INTO TuThien.CITY (id, name, region_id) VALUES (63, 'Tỉnh Cà Mau', 3);
